import type { GameOptions } from "./game_options";

const default_pattern_data = {
  BLESSING_OF_HEAVEN: {
    display_name: "Blessing of Heaven",
    yaku: 20,
    dora: 0,
    fu: 0,
  },
  BLESSING_OF_EARTH: {
    display_name: "Blessing of Earth",
    yaku: 19,
    dora: 0,
    fu: 0,
  },
  LITTLE_THREE_DRAGONS: {
    display_name: "Little Three Dragons",
    yaku: 5,
    dora: 0,
    fu: 0,
  },
  BIG_THREE_DRAGONS: {
    display_name: "Big Three Dragons",
    yaku: 8,
    dora: 0,
    fu: 0,
  },
  FOUR_LITTLE_WINDS: {
    display_name: "Four Little Winds",
    yaku: 12,
    dora: 0,
    fu: 0,
  },
  FOUR_BIG_WINDS: {
    display_name: "Four Big Winds",
    yaku: 16,
    dora: 0,
    fu: 0,
  },
  FOUR_CONCEALED_TRIPLETS: {
    display_name: "Four Concealed Triplets",
    yaku: 12,
    dora: 0,
    fu: 0,
  },
  FOUR_CONCEALED_TRIPLETS_1_SIDED_WAIT: {
    display_name: "Four Concealed Triplets 1-sided Wait",
    yaku: 12,
    dora: 0,
    fu: 0,
  },
  ALL_HONOURS: {
    display_name: "All Honours",
    yaku: 10,
    dora: 0,
    fu: 0,
  },
  ALL_GREENS: {
    display_name: "All Greens",
    yaku: 16,
    dora: 0,
    fu: 0,
  },
  ALL_TERMINALS: {
    display_name: "All Terminals",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  THIRTEEN_ORPHANS: {
    display_name: "Thirteen Orphans",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  THIRTEEN_ORPHANS_13_SIDED_WAIT: {
    display_name: "Thirteen Orphans 13-sided Wait",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  FOUR_QUADS: {
    display_name: "Four Quads",
    yaku: 18,
    dora: 0,
    fu: 0,
  },
  NINE_GATES: {
    display_name: "Nine Gates",
    yaku: 11,
    dora: 0,
    fu: 0,
  },
  TRUE_NINE_GATES: {
    display_name: "True Nine Gates",
    yaku: 19,
    dora: 0,
    fu: 0,
  },
  RIICHI: {
    display_name: "Riichi",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  DOUBLE_RIICHI: {
    display_name: "Double Riichi",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  IPPATSU: {
    display_name: "Ippatsu",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  ALL_SEQUENCES: {
    display_name: "All Sequences",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  ALL_SIMPLES: {
    display_name: "All Simples",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  PURE_STRAIGHT: {
    display_name: "Pure Straight",
    yaku: 3,
    dora: 0,
    fu: 0,
  },
  ALL_TRIPLETS: {
    display_name: "All Triplets",
    yaku: 3,
    dora: 0,
    fu: 0,
  },
  HALF_FLUSH: {
    display_name: "Half Flush",
    yaku: 3,
    dora: 0,
    fu: 0,
  },
  FULL_FLUSH: {
    display_name: "Full Flush",
    yaku: 7,
    dora: 0,
    fu: 0,
  },
  SEVEN_PAIRS: {
    display_name: "Seven Pairs",
    yaku: 3,
    dora: 0,
    fu: 0,
  },
  HALF_OUTSIDE_HAND: {
    display_name: "Half Outside Hand",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  FULLY_OUTSIDE_HAND: {
    display_name: "Fully Outside Hand",
    yaku: 4,
    dora: 0,
    fu: 0,
  },
  PURE_DOUBLE_SEQUENCE: {
    display_name: "Pure Double Sequence",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  TWICE_PURE_DOUBLE_SEQUENCE: {
    display_name: "Twice Pure Double Sequence",
    yaku: 4,
    dora: 0,
    fu: 0,
  },
  PURE_TRIPLE_SEQUENCE: {
    display_name: "Pure Triple Sequence",
    yaku: 6,
    dora: 0,
    fu: 0,
  },
  PURE_QUADRUPLE_SEQUENCE: {
    display_name: "Pure Quadruple Sequence",
    yaku: 12,
    dora: 0,
    fu: 0,
  },
  MIXED_TRIPLE_SEQUENCE: {
    display_name: "Mixed Triple Sequence",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  THREE_CONCEALED_TRIPLETS: {
    display_name: "Three Concealed Triplets",
    yaku: 3,
    dora: 0,
    fu: 0,
  },
  THREE_QUADS: {
    display_name: "Three Quads",
    yaku: 4,
    dora: 0,
    fu: 0,
  },
  TRIPLE_TRIPLETS: {
    display_name: "Triple Triplets",
    yaku: 4,
    dora: 0,
    fu: 0,
  },
  ALL_TERMINALS_AND_HONOURS: {
    display_name: "All Terminals and Honours",
    yaku: 3,
    dora: 0,
    fu: 0,
  },
  SEAT_WIND: {
    display_name: "Seat Wind",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  PREVALENT_WIND: {
    display_name: "Prevalent Wind",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  NORTH_WIND: {
    display_name: "North Wind",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  WHITE_DRAGON: {
    display_name: "White Dragon",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  GREEN_DRAGON: {
    display_name: "Green Dragon",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  RED_DRAGON: {
    display_name: "Red Dragon",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  EYES: {
    display_name: "Eyes",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  NO_CALLS: {
    display_name: "No Calls",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  NO_CALLS_TSUMO: {
    display_name: "No Calls Tsumo",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  ROBBING_A_KAN: {
    display_name: "Robbing a Kan",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  UNDER_THE_SEA: {
    display_name: "Under the Sea",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  UNDER_THE_RIVER: {
    display_name: "Under the River",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  AFTER_A_FLOWER: {
    display_name: "After a Flower",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  AFTER_A_KAN: {
    display_name: "After a Kan",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  DORA: {
    display_name: "Dora",
    yaku: 0,
    dora: 1,
    fu: 0,
  },
  URA_DORA: {
    display_name: "Ura Dora",
    yaku: 0,
    dora: 1,
    fu: 0,
  },
  NO_FLOWERS: {
    display_name: "No Flowers",
    yaku: 0,
    dora: 1,
    fu: 0,
  },
  SEAT_FLOWER: {
    display_name: "Seat Flower",
    yaku: 0,
    dora: 1,
    fu: 0,
  },
  SET_OF_FLOWERS: {
    display_name: "Set of Flowers",
    yaku: 0,
    dora: 2,
    fu: 0,
  },
  FIVE_FLOWERS: {
    display_name: "Five Flowers",
    yaku: 0,
    dora: 2,
    fu: 0,
  },
  SEVEN_FLOWERS: {
    display_name: "Seven Flowers",
    yaku: 0,
    dora: 2,
    fu: 0,
  },
  TWO_SETS_OF_FLOWERS: {
    display_name: "Two Sets of Flowers",
    yaku: 0,
    dora: 8,
    fu: 0,
  },
  DRAW: {
    display_name: "Draw",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  OPEN_WAIT: {
    display_name: "Open Wait",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  CLOSED_WAIT: {
    display_name: "Closed Wait",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
  EDGE_WAIT: {
    display_name: "Edge Wait",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
  DUAL_PON_WAIT: {
    display_name: "Dual Pon Wait",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  PAIR_WAIT: {
    display_name: "Pair Wait",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
  SIMPLE_OPEN_TRIPLET: {
    display_name: "Simple Open Triplet",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
  ORPHAN_OPEN_TRIPLET: {
    display_name: "Orphan Open Triplet",
    yaku: 0,
    dora: 0,
    fu: 4,
  },
  SIMPLE_CLOSED_TRIPLET: {
    display_name: "Simple Closed Triplet",
    yaku: 0,
    dora: 0,
    fu: 4,
  },
  ORPHAN_CLOSED_TRIPLET: {
    display_name: "Orphan Closed Triplet",
    yaku: 0,
    dora: 0,
    fu: 8,
  },
  SIMPLE_OPEN_QUAD: {
    display_name: "Simple Open Quad",
    yaku: 0,
    dora: 0,
    fu: 8,
  },
  ORPHAN_OPEN_QUAD: {
    display_name: "Orphan Open Quad",
    yaku: 0,
    dora: 0,
    fu: 16,
  },
  SIMPLE_CLOSED_QUAD: {
    display_name: "Simple Closed Quad",
    yaku: 0,
    dora: 0,
    fu: 16,
  },
  ORPHAN_CLOSED_QUAD: {
    display_name: "Orphan Closed Quad",
    yaku: 0,
    dora: 0,
    fu: 32,
  },
  YAKUHAI_PAIR: {
    display_name: "Yakuhai Pair",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
  CLOSED_PINFU: {
    display_name: "Pinfu",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  OPEN_PINFU: {
    display_name: "Open Pinfu",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
  NO_CALLS_RON: {
    display_name: "No Calls Ron",
    yaku: 0,
    dora: 0,
    fu: 10,
  },
  NON_PINFU_TSUMO: {
    display_name: "Non Pinfu Tsumo",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
};

const default_preset = {
  game_length_wind_rounds: 1,
  game_length_sub_rounds: 0,
  use_flowers: true,
  auto_replace_flowers: true,
  min_yaku: 0,
  allow_riichi: true,
  allow_rob_added_kan: true,
  allow_thirteen_orphans_rob_closed_kan: true,
  allow_rob_closed_kan: false,
  use_temporary_furiten: true,
  use_riichi_furiten: true,
  use_own_discard_furiten: true,
  show_waits: true,
  show_shanten_info: false,
  max_kan_count: 4,
  max_dora_count: 5,
  start_dora_count: 1,
  dead_wall_additional_tiles: 0,
  start_score: 0,
  calculate_fu: true,
  base_fu: 20,
  seven_pairs_use_fixed_fu: true,
  seven_pairs_fixed_fu: 25,
  round_up_fu: false,
  round_up_points: false,
  base_score_limits: [{ han: 6, score: 6400 }, { han: 10, score: 12800 }],
  pattern_data: default_pattern_data,
};

export const default_4player_preset: GameOptions = {
  ...default_preset,
  player_count: 4,
  score_dealer_ron_multiplier: 6,
  score_dealer_tsumo_multiplier: 2,
  score_nondealer_ron_multiplier: 4,
  score_nondealer_tsumo_nondealer_multiplier: 1,
  score_nondealer_tsumo_dealer_multiplier: 2,
};

export const default_3player_preset: GameOptions = {
  ...default_preset,
  player_count: 3,
  score_dealer_ron_multiplier: 6,
  score_dealer_tsumo_multiplier: 3,
  score_nondealer_ron_multiplier: 4,
  score_nondealer_tsumo_nondealer_multiplier: 1.5,
  score_nondealer_tsumo_dealer_multiplier: 2.5,
};

const riichi_pattern_data = {
  BLESSING_OF_HEAVEN: {
    display_name: "Blessing of Heaven",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  BLESSING_OF_EARTH: {
    display_name: "Blessing of Earth",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  LITTLE_THREE_DRAGONS: {
    display_name: "Little Three Dragons",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  BIG_THREE_DRAGONS: {
    display_name: "Big Three Dragons",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  FOUR_LITTLE_WINDS: {
    display_name: "Four Little Winds",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  FOUR_BIG_WINDS: {
    display_name: "Four Big Winds",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  FOUR_CONCEALED_TRIPLETS: {
    display_name: "Four Concealed Triplets",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  FOUR_CONCEALED_TRIPLETS_1_SIDED_WAIT: {
    display_name: "Four Concealed Triplets 1-sided Wait",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  ALL_HONOURS: {
    display_name: "All Honours",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  ALL_GREENS: {
    display_name: "All Greens",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  ALL_TERMINALS: {
    display_name: "All Terminals",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  THIRTEEN_ORPHANS: {
    display_name: "Thirteen Orphans",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  THIRTEEN_ORPHANS_13_SIDED_WAIT: {
    display_name: "Thirteen Orphans 13-sided Wait",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  FOUR_QUADS: {
    display_name: "Four Quads",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  NINE_GATES: {
    display_name: "Nine Gates",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  TRUE_NINE_GATES: {
    display_name: "True Nine Gates",
    yaku: 13,
    dora: 0,
    fu: 0,
  },
  RIICHI: {
    display_name: "Riichi",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  DOUBLE_RIICHI: {
    display_name: "Double Riichi",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  IPPATSU: {
    display_name: "Ippatsu",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  ALL_SEQUENCES: {
    display_name: "All Sequences",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  ALL_SIMPLES: {
    display_name: "All Simples",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  PURE_STRAIGHT: {
    display_name: "Pure Straight",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  ALL_TRIPLETS: {
    display_name: "All Triplets",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  HALF_FLUSH: {
    display_name: "Half Flush",
    yaku: 3,
    dora: 0,
    fu: 0,
  },
  FULL_FLUSH: {
    display_name: "Full Flush",
    yaku: 6,
    dora: 0,
    fu: 0,
  },
  SEVEN_PAIRS: {
    display_name: "Seven Pairs",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  HALF_OUTSIDE_HAND: {
    display_name: "Half Outside Hand",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  FULLY_OUTSIDE_HAND: {
    display_name: "Fully Outside Hand",
    yaku: 3,
    dora: 0,
    fu: 0,
  },
  PURE_DOUBLE_SEQUENCE: {
    display_name: "Pure Double Sequence",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  TWICE_PURE_DOUBLE_SEQUENCE: {
    display_name: "Twice Pure Double Sequence",
    yaku: 3,
    dora: 0,
    fu: 0,
  },
  PURE_TRIPLE_SEQUENCE: {
    display_name: "Pure Triple Sequence",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  PURE_QUADRUPLE_SEQUENCE: {
    display_name: "Pure Quadruple Sequence",
    yaku: 3,
    dora: 0,
    fu: 0,
  },
  MIXED_TRIPLE_SEQUENCE: {
    display_name: "Mixed Triple Sequence",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  THREE_CONCEALED_TRIPLETS: {
    display_name: "Three Concealed Triplets",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  THREE_QUADS: {
    display_name: "Three Quads",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  TRIPLE_TRIPLETS: {
    display_name: "Triple Triplets",
    yaku: 2,
    dora: 0,
    fu: 0,
  },
  ALL_TERMINALS_AND_HONOURS: {
    display_name: "All Terminals and Honours",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  SEAT_WIND: {
    display_name: "Seat Wind",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  PREVALENT_WIND: {
    display_name: "Prevalent Wind",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  NORTH_WIND: {
    display_name: "North Wind",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  WHITE_DRAGON: {
    display_name: "White Dragon",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  GREEN_DRAGON: {
    display_name: "Green Dragon",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  RED_DRAGON: {
    display_name: "Red Dragon",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  EYES: {
    display_name: "Eyes",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  NO_CALLS: {
    display_name: "No Calls",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  NO_CALLS_TSUMO: {
    display_name: "No Calls Tsumo",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  ROBBING_A_KAN: {
    display_name: "Robbing a Kan",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  UNDER_THE_SEA: {
    display_name: "Under the Sea",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  UNDER_THE_RIVER: {
    display_name: "Under the River",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  AFTER_A_FLOWER: {
    display_name: "After a Flower",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  AFTER_A_KAN: {
    display_name: "After a Kan",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  DORA: {
    display_name: "Dora",
    yaku: 0,
    dora: 1,
    fu: 0,
  },
  URA_DORA: {
    display_name: "Ura Dora",
    yaku: 0,
    dora: 1,
    fu: 0,
  },
  NO_FLOWERS: {
    display_name: "No Flowers",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  SEAT_FLOWER: {
    display_name: "Seat Flower",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  SET_OF_FLOWERS: {
    display_name: "Set of Flowers",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  FIVE_FLOWERS: {
    display_name: "Five Flowers",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  SEVEN_FLOWERS: {
    display_name: "Seven Flowers",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  TWO_SETS_OF_FLOWERS: {
    display_name: "Two Sets of Flowers",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  DRAW: {
    display_name: "Draw",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  OPEN_WAIT: {
    display_name: "Open Wait",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  CLOSED_WAIT: {
    display_name: "Closed Wait",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
  EDGE_WAIT: {
    display_name: "Edge Wait",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
  DUAL_PON_WAIT: {
    display_name: "Dual Pon Wait",
    yaku: 0,
    dora: 0,
    fu: 0,
  },
  PAIR_WAIT: {
    display_name: "Pair Wait",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
  SIMPLE_OPEN_TRIPLET: {
    display_name: "Simple Open Triplet",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
  ORPHAN_OPEN_TRIPLET: {
    display_name: "Orphan Open Triplet",
    yaku: 0,
    dora: 0,
    fu: 4,
  },
  SIMPLE_CLOSED_TRIPLET: {
    display_name: "Simple Closed Triplet",
    yaku: 0,
    dora: 0,
    fu: 4,
  },
  ORPHAN_CLOSED_TRIPLET: {
    display_name: "Orphan Closed Triplet",
    yaku: 0,
    dora: 0,
    fu: 8,
  },
  SIMPLE_OPEN_QUAD: {
    display_name: "Simple Open Quad",
    yaku: 0,
    dora: 0,
    fu: 8,
  },
  ORPHAN_OPEN_QUAD: {
    display_name: "Orphan Open Quad",
    yaku: 0,
    dora: 0,
    fu: 16,
  },
  SIMPLE_CLOSED_QUAD: {
    display_name: "Simple Closed Quad",
    yaku: 0,
    dora: 0,
    fu: 16,
  },
  ORPHAN_CLOSED_QUAD: {
    display_name: "Orphan Closed Quad",
    yaku: 0,
    dora: 0,
    fu: 32,
  },
  YAKUHAI_PAIR: {
    display_name: "Yakuhai Pair",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
  CLOSED_PINFU: {
    display_name: "Pinfu",
    yaku: 1,
    dora: 0,
    fu: 0,
  },
  OPEN_PINFU: {
    display_name: "Open Pinfu",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
  NO_CALLS_RON: {
    display_name: "No Calls Ron",
    yaku: 0,
    dora: 0,
    fu: 10,
  },
  NON_PINFU_TSUMO: {
    display_name: "Non Pinfu Tsumo",
    yaku: 0,
    dora: 0,
    fu: 2,
  },
};

const riichi_preset = {
  game_length_wind_rounds: 1,
  game_length_sub_rounds: 0,
  use_flowers: false,
  auto_replace_flowers: true,
  min_yaku: 1,
  allow_riichi: true,
  allow_rob_added_kan: true,
  allow_thirteen_orphans_rob_closed_kan: true,
  allow_rob_closed_kan: false,
  use_temporary_furiten: true,
  use_riichi_furiten: true,
  use_own_discard_furiten: true,
  show_waits: true,
  max_kan_count: 4,
  max_dora_count: 5,
  start_dora_count: 1,
  dead_wall_additional_tiles: 0,
  calculate_fu: true,
  base_fu: 20,
  round_up_fu: true,
  seven_pairs_use_fixed_fu: true,
  seven_pairs_fixed_fu: 25,
  round_up_points: true,
  show_shanten_info: false,
  base_score_limits: [
    { han: 5, score: 2000 },
    { han: 6, score: 3000 },
    { han: 8, score: 4000 },
    { han: 11, score: 6000 },
    { han: 13, score: 8000 },
  ],
  pattern_data: riichi_pattern_data,
};

export const riichi_4player_preset: GameOptions = {
  ...riichi_preset,
  player_count: 4,
  start_score: 25000,
  score_dealer_ron_multiplier: 6,
  score_dealer_tsumo_multiplier: 2,
  score_nondealer_ron_multiplier: 4,
  score_nondealer_tsumo_nondealer_multiplier: 1,
  score_nondealer_tsumo_dealer_multiplier: 2,
};

export const riichi_3player_preset: GameOptions = {
  ...riichi_preset,
  player_count: 3,
  start_score: 35000,
  score_dealer_ron_multiplier: 6,
  score_dealer_tsumo_multiplier: 3,
  score_nondealer_ron_multiplier: 4,
  score_nondealer_tsumo_nondealer_multiplier: 1.5,
  score_nondealer_tsumo_dealer_multiplier: 2.5,
};
